- hosts: network-interfaces
  become: yes

  roles:
  - role: dresden-weekly.network-interfaces
    network_manage_devices: yes
    network_restart_method: interface

    network_interfaces:
    - device: eth0
      description: just a description for humans to understand!
      auto: true
      family: inet

    - device: eth1
      description: simple dhcp client interface!
      auto: true
      family: inet
      method: dhcp

    - device: vlan123
      description: sample vlan interface using eth0 and tagged for VLAN 123.
      method: static
      address: 1.2.3.4
      netmask: 24
      broadcast: 1.2.3.255
      vlan-raw-device: eth0
      up:
      - route add default gw 1.2.3.254

    - device: vlan123
      allow:
        - hotplug
      description: secondary ip
      method: static
      address: 1.2.3.6
      netmask: 24
      broadcast: 1.2.3.255
      vlan-raw-device: eth0
